version: "3.9"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: guestbook-db
    networks:
      - guestbook-net
    volumes:
      - mongo_data:/data/db

  # Backend API
  api:
    # build: ./backend
    image: backend
    container_name: guestbook-api
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - guestbook-net

  # Frontend
  web:
    # build: ./frontend
    image: frontend
    container_name: guestbook-web
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - guestbook-net

networks:
  guestbook-net:

volumes:
  mongo_data:
